### ISSUE TITLE
Remove LinkedList

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#223]
`LinkedList` is significant overhead meaningfully and from the performance view.

Built-in `Array` has the same functionality so it can be easily achieved by wrapping or extending the `Array`. The interface can stay the same but the class should be renamed more appropriate like `ChunkArray` or `ChunkList`.

**Comment by Joozty** [comment]
Can you please share with me the performance insights?

**Comment by viktor-yakubiv** [comment]
I consider the current implementation being slow. I had just a feeling but your question sounded so picky I finally decided to take this challenge. And the **results made me wonder a lot**, the difference is much bigger than I expected.

### Algorithm

I used the benchmarking code with the following configuration:

- Bucket size: 100
- Count of buckets: 1000
- Count of operations: 1 000 000

The snippet itself:

```js
const CHUNK_SIZE = 1e2
const CHUNKS_COUNT = 1e3
const TEST_ITERATIONS = 1e6
const chunk = Array.from(Array(CHUNK_SIZE), (_, i) => i)

const testOne = (List, size = CHUNKS_COUNT, limit = TEST_ITERATIONS) => {

  const l = new List()
  for (let i = 0; i < size; ++i) l.add(chunk)
  
  const start = Date.now()
  let total = 0
  for (let i = 0; i < limit; ++i) {
    const index = (CHUNKS_COUNT - 1) * CHUNK_SIZE + 1
    let x = l.get(index)
    total = (total + x) % 100 // avoid optimisations
  }
  const end = Date.now()
  
  return [start, end]
}

const test = () => {
  const [ta1, ta2] = testOne(LinkedList)
  const [tb1, tb2] = testOne(ChunkList)
  const [tc1, tc2] = testOne(ExtendedArray)

  const ta = ta2 - ta1
  const tb = tb2 - tb1
  const tc = tc2 - tc1

  return {
    'LinkedList': ta, 
    'ChunkedList': tb,
    'Array': tc,
    'LinkedList / ChunkedList': ta / tb,
    'LinkedList / Array': ta / tc,
  }
}
```

### What's been benchmarked?

The `LinkedList` is used from the project.

The `ChunkedList` is a simple optimisation based on the built-in Array written by myself:

```js
class ChunkList {
  constructor(size) {
    this.chunkSize = size
    this.chunks = []
    this.done = false
  }

  add(chunk) {
    if (this.done) throw new Error('Only one chunk and have different size')
    this.chunks.push(chunk)
    
    const previous = this.chunks[this.chunks.length - 2]
    if (previous != null && chunk.size !== this.chunkSize) this.done = true
  }

  get(i) {
    const chunk = this.chunks[Math.floor(i / this.chunkSize)]
    if (chunk == null) return undefined
    return chunk[i % this.chunkSize]
  }
}
```

The ExtendedArray is as simple as:

```js
class ExtendedArray extends Array {
  add(chunk) {
    this.push(...chunk)
  }

  get(i) {
    return this[i]
  }
}
```

### Results

- `ChunkList` is 1.6 times faster than `LinkedList`
- Pure `Array` is **87 times** faster than `LinkedList` ❗️

#### Actual output

```
{
  LinkedList: 1582,
  ChunkedList: 986,
  Array: 18,
  'LinkedList / ChunkedList': 1.6044624746450304,
  'LinkedList / Array': 87.88888888888889
}
```

**Comment by Joozty** [comment]
Thanks for providing me with tests. I don't think they reflect the real application. `get` is not used at all. Also Table component keeps its own array with row references so it doesn't use a linked list. However, I see your point and it's good that you pointed it out. Even if you used different methods the pure array would still win. There is no doubt.

Quite frankly Table component was over-engineered from the beginning. LinkedList should have been removed along with https://github.com/oacore/dashboard/pull/139. There is no need for it now. (probably there never has been). I don't see anything stopping us. 

So as an output of this task these three points need to be fulfilled.
1. Remove [linked list](https://github.com/oacore/dashboard/tree/master/utils).
2. Remove [Page class](https://github.com/oacore/dashboard/blob/master/store/helpers/pages/page.js)
3. Replace LinkedList [here](https://github.com/oacore/dashboard/blob/master/store/helpers/pages/pages.js#L13) with simple array and do appropriate changes in Pages class.


I assigned the task to you because I find it a great opportunity for you to get to know the table component better.
