### ISSUE TITLE
Split data provider request from the user endpoint

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#390]
We are in a need to enable opening any data provider in spite of having access to it or not. It's needed for the content managers to be able to understand how the user actually sees the application.

It would be nice to have **view as** functionality but this requires some work on the API. At the moment, we should adjust our model and app behaviour accordingly.

### Requirements

1. The application during the initialisation should immediately request data provider information from `/data-providers/{id}` even if the `/user` is not loaded.
2. The data provider is not shown until the data about the user is not loaded but when everything is retrieved:
   - if the user is admin (the are a few options), it shows the data provider even if the data provider is not in the list
      - maybe it even adds the data provider to the list
   - if the user is not admin, it performs the check we have now and either shows the data or 403 error (without a redirect)
      - can be without any error at the first step, with the redirect
      - the error page is preferable because it's more transparent to the user

### Implementation details

I propose to create a **DataProvider** store that handles almost everything that the Root store does now. Since all the data is under the DataProvider store, we will get proper loading for the statistics and other data when the data provider switches.

**Comment by Joozty** [comment]
It may be a little bit tricky to make `/data-providers/{id}` request before `/user`.  It would be better if we fire it straight after /user.

My concerns:
1. user endpoint is used for checking if the user is is logged in.  (if data provider endpoint  is behind a firewall it may be solved but still, we may fire a useless request if a user is not logged in)
2. currently the API doesn't check if the user has access for dataProvider. So it may happen that the user loads all data but the dashboard won't show it because of access. 
3. and obvioslu it's hard to implement (not a valid reason though) 😄 

I would do it slightly differently:

1. call /user
2. changeDataProvider
3. check if user has access to dataProvider
   - if not return 404 or redirect to first available
   - if user is admin call dataProvider endpoint [here](https://github.com/oacore/dashboard/blob/master/store/root.js#L113) and append retrieved data to the list.


--- 
Independently on the login flow, the dataProvider substore is a good idea and the kick off PR is here https://github.com/oacore/dashboard/pull/395

**Comment by viktor-yakubiv** [comment]
I described it in a way I did because I wanted to speed up the endpoint. The API does not do it because the data provider is public, it can be accessed in the same way, let's say from `core.ac.uk/data-providers/{id}` but cannot be modified from there.

That is why I see the dashboard completely open and the current restrictions are fake. However, it's not a problem here, we should be able to switch this fake on or off when needed using a flag `allowAnonymousAccess`. Anyway, it's a separate discussion.

#395 is a good start. Let's see what we can do with when we merge the PR.

**Comment by Joozty** [comment]
I assume this can be closed. We implemented it in some way already.
